### PR TITLE
Link MongoDB

### PR DESCRIPTION
**Pull request by dostuffthatmatters**
Registration and Login now implemented with the database.

All asynchronous operations are also implemented asynchronously.

@empicano I will add rich test with the next PR. Just give me a bit of feedback whether you agree with the architecture style or find any big mistakes.

### CODE REVIEW

**Comment by empicano** [comment]
Usually the FastAPI projects I saw followed the structure of putting the routes in a `main.py` and leaving the `__init__.py` empty. For this see tiangolo's Full Stack FastAPI Base Project.

**Comment by empicano** [comment]
As far as I know the convention with shell scripts is to name them *.sh and specify your specific shell as e.g. `#!/bin/bash` (whereas I think you're running zsh with your Mac so `#!/bin/zsh`). Even better would be to keep it as generic shell script via `#!/bin/sh`

**Comment by empicano** [comment]
Otherwise it looks good! I didn't understand everything in a glance, but that I'll do when I'm finished with the graphs 😌

**Comment by dostuffthatmatters** [comment]
Will look into the file splitting convention! They seem to be using the APIRouter class. I will read more about that.

**Comment by dostuffthatmatters** [comment]
Just updated the extensions of the shell scripts.

**Pull request merged**
